# -*- coding: utf-8 -*-
"""Copy of Sentiment Analysis on Movie Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjgvRRGQ2BWOmMvEhoQh06FbG0FTW1Dn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**download data**"""

df = pd.read_csv("IMDB Dataset.csv")
print(df.head())

"""**Preprocessing**"""

#clean text
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"<.*?>", "", text)  # حذف HTML
    text = re.sub(r"[^a-zA-Z]", " ", text)
    return text

df["review"] = df["review"].apply(clean_text)

#Tokenization
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Limits the vocabulary to the top 10000 most frequent words

tokenizer = Tokenizer(num_words=10000)

tokenizer.fit_on_texts(df["review"])

X = tokenizer.texts_to_sequences(df["review"])
#Pads all sequences to a fixed length (200) to ensure uniform input size for the model
X = pad_sequences(X, maxlen=200)

# Convert sentiment labels from text to binary values:
# 'positive' is mapped to 1
# 'negative' is mapped to 0
y = df["sentiment"].map({"positive":1, "negative":0})
print(y.head())

"""**split data**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

"""**Build LSTM Model**"""

# Build an LSTM-based deep learning model for sentiment analysis
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=128))

model.add(Bidirectional(LSTM(64, dropout=0.4)))

model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2,
    callbacks=[early_stop]
)

model.evaluate(X_test, y_test)

def predict_sentiment(text):
    text = clean_text(text)
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=200)
    prediction = model.predict(padded)[0][0]

    return "Positive" if prediction > 0.5 else "Negative"

print(predict_sentiment("This movie was amazing!"))

def predict_sentiment(text):
    text_clean = clean_text(text)
    seq = tokenizer.texts_to_sequences([text_clean])
    padded = pad_sequences(seq, maxlen=200)

    prediction = model.predict(padded, verbose=0)[0][0]

    label = "Positive" if prediction > 0.5 else "Negative"
    confidence = float(prediction) if prediction > 0.5 else 1 - float(prediction)

    return label, confidence


# =========================
# 1. اختبار جمل جاهزة
# =========================
test_sentences = [
    "This movie was amazing!",
    "I hated this film, it was terrible",
    "It was okay, nothing special",
    "Best movie I have ever seen",
    "Waste of time"
]

print("\n🔹 Manual Test Results:\n")
for t in test_sentences:
    label, conf = predict_sentiment(t)
    print(f"Text: {t}")
    print(f"Prediction: {label} | Confidence: {conf:.2f}")
    print("-" * 50)


# =========================
# 2. اختبار عشوائي من الداتا
# =========================
print("\n🔹 Random Dataset Test:\n")

sample = df.sample(10)

for _, row in sample.iterrows():
    text = row["review"]
    true_label = row["sentiment"]

    pred_label, conf = predict_sentiment(text)

    print(f"Text: {text[:100]}...")
    print(f"True: {true_label} | Pred: {pred_label} | Confidence: {conf:.2f}")
    print("-" * 50)